name: build asciidoctor
on: [push]

jobs:
  build_index:
    name: generate index html
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mgred/asciidoctor-action@master
      with:
        entrypoint: asciidoctor
        args: index.adoc
    - uses: mgred/asciidoctor-action@master
      with:
        entrypoint: asciidoctor
        args: cv/cv.adoc
    - uses: mgred/asciidoctor-action@master
      with:
        args: cat cv/cv.html
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}