name: build asciidoctor
on: [push]

jobs:
  build_index:
    name: generate index html
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mgred/asciidoctor-action@master
      with:
        entrypoint: asciidoctor
        args: index.adoc
    - uses: mgred/asciidoctor-action@master
      with:
        entrypoint: asciidoctor
        args: cv/cv.adoc
    - uses: mgred/asciidoctor-action@master
      with:
        args: cat cv/cv.html
  